services:
 python-backend:
  build:
   context: ./PythonBackend/combined_app
   dockerfile: Dockerfile
  volumes:
   - .:/python-backend-volume
   - ./PythonBackend/combined_app/uploads:/python-backend-volume/uploads
  ports:
   - "${PORT:-5001}:${PORT:-5001}"
  environment:
   - MONGO_URI=mongodb://mongodb:27017/the-menufy
  env_file: ./PythonBackend/combined_app/.env
  networks:
   - menufy-network
  depends_on:
   - mongodb
 express-backend:
  build:
   context: .
   dockerfile: Dockerfile
  volumes:
   - .:/express-backend-volume
  ports:
   - "${PORT:-5000}:${PORT:-5000}"
  environment:
   - MONGO_URI=mongodb://mongodb:27017/the-menufy
   - FRONTEND_URL=http://localhost:5173/vite/demo
  env_file: .env
  networks:
   - menufy-network
  depends_on:
   - mongodb
 mongodb:
  image: mongo:latest
  ports:
   - "27017:27017"
  volumes:
   - mongodb-data:/data/db
  networks:
   - menufy-network
volumes:
 python-backend-volume:
 express-backend-volume:
 mongodb-data:
networks:
 menufy-network:
  driver: bridge
