const mongoose = require("mongoose");
const {
  restaurant1Id,
  restaurant2Id,
  restaurant3Id,
} = require("./restaurantSeeds");
const { category1Id, category2Id, category3Id } = require("./categorySeeds");

const stock1Id = new mongoose.Types.ObjectId();
const stock2Id = new mongoose.Types.ObjectId();
const stock3Id = new mongoose.Types.ObjectId();
const stock4Id = new mongoose.Types.ObjectId();
const stock5Id = new mongoose.Types.ObjectId();
const stock6Id = new mongoose.Types.ObjectId();
const stock7Id = new mongoose.Types.ObjectId();
const stock8Id = new mongoose.Types.ObjectId();
const stock9Id = new mongoose.Types.ObjectId();
const stock10Id = new mongoose.Types.ObjectId();
const stock11Id = new mongoose.Types.ObjectId();
const stock12Id = new mongoose.Types.ObjectId();

const stocks = [
  {
    _id: stock1Id,
    libelle: "Milk",
    quantity: 50,
    inventory: 50,
    type: category1Id,
    price: 11.99,
    disponibility: true,
    maxQty: 100,
    minQty: 10,
    unit: "l",
    restaurant: restaurant1Id,
    shelfLifeDays: 7,
  },
  {
    _id: stock2Id,
    libelle: "Beef",
    quantity: 25,
    inventory: 25,
    type: category2Id,
    price: 8.99,
    disponibility: true,
    maxQty: 50,
    minQty: 5,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 14,
  },
  {
    _id: stock3Id,
    libelle: "Tomatoes",
    quantity: 30,
    inventory: 30,
    type: category3Id,
    price: 3.49,
    disponibility: true,
    maxQty: 60,
    minQty: 8,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 10,
  },
  // Additional stock items
  {
    _id: stock4Id,
    libelle: "Flour",
    quantity: 100,
    inventory: 100,
    type: category1Id,
    price: 2.99,
    disponibility: true,
    maxQty: 200,
    minQty: 20,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 180,
  },
  {
    _id: stock5Id,
    libelle: "Sugar",
    quantity: 75,
    inventory: 75,
    type: category1Id,
    price: 3.49,
    disponibility: true,
    maxQty: 150,
    minQty: 15,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 365,
  },
  {
    _id: stock6Id,
    libelle: "Chicken",
    quantity: 40,
    inventory: 40,
    type: category2Id,
    price: 7.99,
    disponibility: true,
    maxQty: 80,
    minQty: 10,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 7,
  },
  {
    _id: stock7Id,
    libelle: "Potatoes",
    quantity: 60,
    inventory: 60,
    type: category3Id,
    price: 2.49,
    disponibility: true,
    maxQty: 120,
    minQty: 15,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 30,
  },
  {
    _id: stock8Id,
    libelle: "Olive Oil",
    quantity: 20,
    inventory: 20,
    type: category1Id,
    price: 15.99,
    disponibility: true,
    maxQty: 40,
    minQty: 5,
    unit: "l",
    restaurant: restaurant1Id,
    shelfLifeDays: 180,
  },
  {
    _id: stock9Id,
    libelle: "Rice",
    quantity: 80,
    inventory: 80,
    type: category1Id,
    price: 4.99,
    disponibility: true,
    maxQty: 160,
    minQty: 20,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 365,
  },
  {
    _id: stock10Id,
    libelle: "Salmon",
    quantity: 15,
    inventory: 15,
    type: category2Id,
    price: 19.99,
    disponibility: true,
    maxQty: 30,
    minQty: 5,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 5,
  },
  {
    _id: stock11Id,
    libelle: "Onions",
    quantity: 45,
    inventory: 45,
    type: category3Id,
    price: 1.99,
    disponibility: true,
    maxQty: 90,
    minQty: 10,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 30,
  },
  {
    _id: stock12Id,
    libelle: "Cheese",
    quantity: 35,
    inventory: 35,
    type: category1Id,
    price: 12.99,
    disponibility: true,
    maxQty: 70,
    minQty: 8,
    unit: "kg",
    restaurant: restaurant1Id,
    shelfLifeDays: 21,
  },
];

module.exports = {
  stocks,
  stock1Id,
  stock2Id,
  stock3Id,
  stock4Id,
  stock5Id,
  stock6Id,
  stock7Id,
  stock8Id,
  stock9Id,
  stock10Id,
  stock11Id,
  stock12Id,
};
